const data = [
    {
      key: '1',
      sifra: 2322,
      head_type: "BSP ADAPTERI",
      type: "TESTIK MASKO - MASKO - MASKO (M+M+M)",
      cena: 392.69,
      komada: 15274,
      opis: '1"M+M+M',
    },
    {
      key: '2',
      sifra: 4,
      head_type: "BSP ADAPTERI",
      type: "TESTIK MASKO - MASKO - MASKO (M+M+M)",
      cena: 38.99,
      komada: 15114,
      opis: "Dicsa",
    },
    {
      key: '3',
      sifra: 4,
      head_type: "BSP ADAPTERI",
      type: "TESTIK MASKO - MASKO - MASKO (M+M+M)",
      cena: 475.48,
      komada: 15214,
      opis: "Dicsa",
    },
    {
      key: '4',
      sifra: 4,
      head_type: "BSP ADAPTERI",
      type: "TESTIK MASKO - MASKO - MASKO (M+M+M)",
      cena: 378.02,
      komada: 15224,
      opis: "Dicsa",
    },
    {
      key: '5',
      sifra: 4,
      head_type: "BSP ADAPTERI",
      type: "TESTIK MASKO - MASKO - MASKO (M+M+M)",
      cena: 608.24,
      komada: 15275,
      opis: '1"1/4M+M+M',
    },
    {
      key: '6',
      sifra: 5,
      head_type: "BSP ADAPTERI",
      type: "KOLENO MASKO - MASKO (M+M)",
      cena: 363.49,
      komada: 15226,
      opis: '1"1/2-1"1/4M+M',
    },
    {
      key: '7',
      sifra: 5,
      head_type: "BSP ADAPTERI",
      type: "KOLENO MASKO - MASKO (M+M)",
      cena: 219.86,
      komada: 15265,
      opis: '5/8"M+M',
    },
    {
      key: '8',
      sifra: 5,
      head_type: "BSP ADAPTERI",
      type: "KOLENO MASKO - MASKO (M+M)",
      cena: 460.04,
      komada: 15268,
      opis: '1"1/4M+M',
    },  
    {
      key: '9',
      sifra: 5,
      head_type: "BSP ADAPTERI",
      type: "KOLENO MASKO - MASKO (M+M)",
      cena: 460.04,
      komada: 15268,
      opis: '1"1/4M+M',
    },  
    {
      key: '10',
      sifra: 5,
      head_type: "BSP ADAPTERI",
      type: "KOLENO MASKO - MASKO (M+M)",
      cena: 460.04,
      komada: 15268,
      opis: '1"1/4M+M',
    },  
    {
      key: '12',
      sifra: 5,
      head_type: "BSP ADAPTERI",
      type: "KOLENO MASKO - MASKO (M+M)",
      cena: 460.04,
      komada: 15268,
      opis: '1"1/4M+M',
    },  
    {
      key: '13',
      sifra: 5,
      head_type: "BSP ADAPTERI",
      type: "KOLENO MASKO - MASKO (M+M)",
      cena: 460.04,
      komada: 15268,
      opis: '1"1/4M+M',
    },  
    {
      key: '14',
      sifra: 5,
      head_type: "BSP ADAPTERI",
      type: "KOLENO MASKO - MASKO (M+M)",
      cena: 460.04,
      komada: 15268,
      opis: '1"1/4M+M',
    },  
  ];
  
  export default data;